version: "3.0"
services:
  dockerapp:
    build: .
    ports:
      - "5002:5000"
    depends_on:
      - redis
    networks:
      - my_net
  redis:
    image: redis
    networks:
      - my_net
networks:
  my_net:
    driver: bridge